description: >
  Retrieve pre-calibrated Docker image as primary code executor
docker:
  - image: 'schradert/flutter-firebase-alpine:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific image variant @ https://hub.docker.com/repository/docker/tristanschrader/flutter-firebase-alpine
    type: string
